### ISSUE TITLE
Look for .TSX test files as well

### ISSUE THREAD

**Issue by ngbrown** [DefinitelyTyped/definition-tester#11]
Now with TypeScript 1.6 released and supporting JSX style files in the form of `.TSX`.  It would be great if the DefinitelyTyped tests could be written as a `-tests.TSX` file.  It's fairly awkward to use `React.CreateElement()` everywhere, especially when they are nested.

**Comment by johnnyreilly** [comment]
This is a very good idea - looks like @vvakame agrees!

**Comment by ngbrown** [comment]
I patch the dist files to make it work, but when I tried to modify the `definition-tester` source files, it wouldn't build with TypeScript 1.6.  I think this is everything I changed, so we don't duplicate too much effort:

`tsc/Tsc.js`:
```js
    var useJsx = /\.tsx$/i;
...
            if (useJsx.test(tsfile)) {
                command += '--jsx react ';
            }
```

`file/fileIndex.js`
```js
        var ok = /\.tsx?$/.test(fileName) && /^[a-z]/i.test(fileName);
...
        return util.glob('**/*.ts*(x)', {
```

**Comment by vvakame** [comment]
I like your idea too :+1: 
but I'm reviewing DefinitelyTyped repo first. please wait.

**Comment by ngbrown** [comment]
@vvakame No worries.  I had to re-push my pull request anyways.  Have a good day.

**Comment by vvakame** [comment]
:+1:
