### ISSUE TITLE
Cannot target es6

### ISSUE THREAD

**Issue by nmalaguti** [DefinitelyTyped/definition-tester#13]
With Typescript 1.6.2, it is not possible to supply a `module` type when targeting es6.

https://github.com/DefinitelyTyped/definition-tester/blob/master/src/tsc/Tsc.ts#L39 always adds a module type of `commonjs` which means that `es6` can never actually be targeted.

**Comment by vvakame** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react-intl/react-intl-tests.tsx.tscparams
you can use `.tscparams`. is it not satisfied you?

**Comment by nmalaguti** [comment]
It seems that once the `--module` is on the command line, there isn't a way to set it to nothing with tscparams.

This shouldn't be an issue with TypeScript 1.7 which supports `commonjs` modules with an `es6` target.

**Comment by vvakame** [comment]
ah, i know. I will take a look this week.

**Comment by vvakame** [comment]
this issue solved by https://github.com/DefinitelyTyped/definition-tester/pull/17
