### ISSUE TITLE
Run `npm install` for dependencies

### ISSUE THREAD

**Issue by andy-ms** [DefinitelyTyped/definition-tester#35]
Currently the `react-daterange-picker` definitions need a kludge for this: they have a hook in their `package.json`. We should figure out the dependencies (`types-publisher` has code to do this) and install their packages too.
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11335.

**Comment by ghost** [comment]
Fixed by DefinitelyTyped/DefinitelyTyped#11547.
